-- ==================== CLEANUP ====================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE OBF_DATA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE OBF_USERS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE OBF_DATA_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE OBF_USERS_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ==================== SEQUENCES ====================
CREATE SEQUENCE OBF_USERS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE OBF_DATA_SEQ START WITH 1 INCREMENT BY 1;

-- ==================== USERS TABLE ====================
CREATE TABLE OBF_USERS (
    ID            NUMBER PRIMARY KEY,
    USERNAME      VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(64)  NOT NULL,
    FULL_NAME     VARCHAR2(200),
    ROLE          VARCHAR2(20)  DEFAULT 'standard' NOT NULL,
    USER_TYPE     VARCHAR2(30),
    COLLEGE_NAME  VARCHAR2(100),
    CONSTRAINT chk_role CHECK (ROLE IN ('admin', 'standard')),
    CONSTRAINT chk_user_type CHECK (USER_TYPE IN ('college', 'cgs', 'uod', 'research_office') OR USER_TYPE IS NULL)
);

-- ==================== USERS TRIGGER ====================
CREATE OR REPLACE TRIGGER TRG_USERS_BI
BEFORE INSERT ON OBF_USERS FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN 
        SELECT OBF_USERS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL; 
    END IF;
END;
/

-- ==================== DATA TABLE ====================
CREATE TABLE OBF_DATA (
    ID               NUMBER PRIMARY KEY,
    USER_ID          NUMBER NOT NULL REFERENCES OBF_USERS(ID),
    COLLEGE_KEY      VARCHAR2(100) NOT NULL,
    SUBMISSION_MONTH VARCHAR2(7) NOT NULL,
    IND_2_5_D NUMBER, IND_2_5_N NUMBER, IND_2_5_R NUMBER, IND_2_5_MECH VARCHAR2(255),
    IND_3_1_D NUMBER, IND_3_1_N NUMBER, IND_3_1_R NUMBER, IND_3_1_MECH VARCHAR2(255),
    IND_3_3_D NUMBER, IND_3_3_N NUMBER, IND_3_3_R NUMBER, IND_3_3_MECH VARCHAR2(255),
    IND_3_4_D NUMBER, IND_3_4_R NUMBER, IND_3_4_MECH VARCHAR2(255),
    IND_4_4_D NUMBER, IND_4_4_N NUMBER, IND_4_4_R NUMBER, IND_4_4_MECH VARCHAR2(255),
    IND_4_5_D NUMBER, IND_4_5_R NUMBER, IND_4_5_MECH VARCHAR2(255),
    IND_5_1_D NUMBER, IND_5_1_R NUMBER, IND_5_1_MECH VARCHAR2(255),
    IND_5_3_D NUMBER, IND_5_3_N NUMBER, IND_5_3_R NUMBER, IND_5_3_MECH VARCHAR2(255),
    IND_6_1_D NUMBER, IND_6_1_R NUMBER, IND_6_1_MECH VARCHAR2(255),
    IND_6_2_D NUMBER, IND_6_2_R NUMBER, IND_6_2_MECH VARCHAR2(255),
    CREATED_BY  VARCHAR2(100),
    CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_BY  VARCHAR2(100),
    UPDATED_AT  TIMESTAMP,
    CONSTRAINT uq_college_month UNIQUE (COLLEGE_KEY, SUBMISSION_MONTH)
);

-- ==================== DATA TRIGGER ====================
CREATE OR REPLACE TRIGGER TRG_DATA_BI
BEFORE INSERT ON OBF_DATA FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN 
        SELECT OBF_DATA_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL; 
    END IF;
    :NEW.CREATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_DATA_BU
BEFORE UPDATE ON OBF_DATA FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- ==================== SEED DATA ====================
-- Admin (password: admin123)
INSERT INTO OBF_USERS (USERNAME, PASSWORD_HASH, FULL_NAME, ROLE)
VALUES ('admin', '$2a$12$t8lJbYmdZMXrSaHAooDMpuMjkPOk3jymMaYB/KAP04Qql02JVlFZa', 'System Administrator', 'admin');

-- College Users (password: TEST@123)
INSERT INTO OBF_USERS (USERNAME, PASSWORD_HASH, FULL_NAME, ROLE, USER_TYPE, COLLEGE_NAME)
VALUES ('ED', '$2a$12$qySbNPAUV/PPrZslK6PJMO/vftBXjhQzywauAykOr/zHto1PTuiXq', 'College of Education', 'standard', 'college', 'Education');

INSERT INTO OBF_USERS (USERNAME, PASSWORD_HASH, FULL_NAME, ROLE, USER_TYPE, COLLEGE_NAME)
VALUES ('EN', '$2a$12$qySbNPAUV/PPrZslK6PJMO/vftBXjhQzywauAykOr/zHto1PTuiXq', 'College of Engineering', 'standard', 'college', 'Engineering');

INSERT INTO OBF_USERS (USERNAME, PASSWORD_HASH, FULL_NAME, ROLE, USER_TYPE, COLLEGE_NAME)
VALUES ('IT', '$2a$12$qySbNPAUV/PPrZslK6PJMO/vftBXjhQzywauAykOr/zHto1PTuiXq', 'College of Information Technology', 'standard', 'college', 'Information Technology');

INSERT INTO OBF_USERS (USERNAME, PASSWORD_HASH, FULL_NAME, ROLE, USER_TYPE, COLLEGE_NAME)
VALUES ('BE', '$2a$12$qySbNPAUV/PPrZslK6PJMO/vftBXjhQzywauAykOr/zHto1PTuiXq', 'College of Business and Economics', 'standard', 'college', 'Business and Economics');

INSERT INTO OBF_USERS (USERNAME, PASSWORD_HASH, FULL_NAME, ROLE, USER_TYPE, COLLEGE_NAME)
VALUES ('SC', '$2a$12$qySbNPAUV/PPrZslK6PJMO/vftBXjhQzywauAykOr/zHto1PTuiXq', 'College of Sciences', 'standard', 'college', 'Sciences');

-- CGS, UOD, Research Office
INSERT INTO OBF_USERS (USERNAME, PASSWORD_HASH, FULL_NAME, ROLE, USER_TYPE)
VALUES ('CGS', '$2a$12$qySbNPAUV/PPrZslK6PJMO/vftBXjhQzywauAykOr/zHto1PTuiXq', 'College of Graduate Studies', 'standard', 'cgs');

INSERT INTO OBF_USERS (USERNAME, PASSWORD_HASH, FULL_NAME, ROLE, USER_TYPE)
VALUES ('UOD', '$2a$12$qySbNPAUV/PPrZslK6PJMO/vftBXjhQzywauAykOr/zHto1PTuiXq', 'Unit of Development', 'standard', 'uod');

INSERT INTO OBF_USERS (USERNAME, PASSWORD_HASH, FULL_NAME, ROLE, USER_TYPE)
VALUES ('research_office', '$2a$12$qySbNPAUV/PPrZslK6PJMO/vftBXjhQzywauAykOr/zHto1PTuiXq', 'Research Office', 'standard', 'research_office');

COMMIT;

SELECT 'Database schema created successfully!' AS STATUS FROM DUAL;
SELECT USERNAME, ROLE, USER_TYPE, COLLEGE_NAME FROM OBF_USERS ORDER BY ID;